
<?php
// Random PHP Code Generated by LLaMA

// This is a simple example of how to use PHP to retrieve data from a MySQL database

$servername = "localhost";
$username = "your_username";
$password = "your_password";
$dbname = "your_database";

// Create connection
$conn = new mysqli($servername, $username, $password, $dbname);
// Check connection
if ($conn->connect_error) {
    die("Connection failed: " . $conn->connect_error);
}

// Retrieve data from the database
$sql = "SELECT * FROM students";
$result = $conn->query($sql);

// Display the data in a table
echo "<table>";
echo "<tr><th>Firstname</th><th>Lastname</th><th>Age</th></tr>";
while ($row = $result->fetch_assoc()) {
    echo "<tr><td>" . $row["firstname"] . "</td><td>" . $row["lastname"] . "</td><td>" . $row["age"] . "</td></tr>";
}
echo "</table>";

// Close the connection
$conn->close();
?>